language: node_js
sudo: false
cache: yarn
node_js:
  - "node"
script:
  - npm run lint
  - npm test
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
branches:
  only:
    - master
